services:
  web:
    build: .
    container_name: flask-web
    ports:
      - "8081:5000"
    environment:
      DB_HOST: db
      DB_USER: devops
      DB_PASSWORD: devopspass
      DB_NAME: devopsdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: devops
      MYSQL_PASSWORD: devopspass
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

volumes:
  mysql_data: